require 'rubygems'
require 'isolate/now'
require 'rake/testtask'

$:.unshift 'lib'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/helper', 'test/**/test_*.rb']
  t.verbose = true
end
